import './chat';
import './admin';
import './players'
import './maps'
import './bestcps';
import './mapwidget';
import './tmx';
import './announces';
import './tmnf_talimit';
import './tmnf_ui';
import './tmnf_dedimania';
import './debugtool';
import './votes';
import './funcommands';
